version: "3.0"
services:
  dockerapp:
    image: subbiah/dockerapp
    ports:
      - "5000:5000"
    depends_on:
      - redis
    # next you have to add deploy element
    deploy:
      replicas: 2
  redis:
    image: redis:3.2.0
    # deploy:
    #   replicas: 2
